version: "2"
services:
    www:
        build: .
        ports: 
            - $APP_PORT:80
        volumes:
            - $APP_PATH:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: $MYSQL_DB
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASS
            MYSQL_ROOT_PASSWORD: $MYSQL_PASS_ROOT
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./mysql_data:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_PASS
            MYSQL_ROOT_PASSWORD: $MYSQL_PASS_ROOT
volumes:
    persistent:
